
vert1: vert1.lex
	flex vert1.lex
	gcc lex.yy.c -lfl -Wno-implicit-function-declaration -o $@
	rm lex.yy.c

vert2: vert2.lex
	flex vert2.lex
	gcc lex.yy.c -lfl -Wno-implicit-function-declaration -o $@
	rm lex.yy.c

